import type { Metadata } from "next";
import Image from "next/image";
import "../enrich.css";
import Link from "next/link";
import { PageHero } from "@/components/PageHero";
import { site } from "@/lib/site";

export const metadata: Metadata = { title: "Private Parties" };

export default function PartiesPage() { return <><PageHero title="A reason to get everyone together." image="/images/interior.jpeg" imagePosition="center 40%"><p>Bring the family, the team, the old friends, and the ones you have not seen in too long. We have hosted celebrations in Bayside for decades.</p></PageHero><section className="section shell party-grid"><div className="party-card party-card--green reveal"><span className="party-card__symbol">✦</span><h2>Room to celebrate.</h2><p>Our private event space gives your group a place to settle in, toast the occasion, and stay as long as the stories do.</p></div><div className="party-card party-card--paper reveal"><p className="eyebrow">What we can help with</p><ul><li>Family celebrations</li><li>Showers and rehearsal dinners</li><li>Work gatherings</li><li>Lunches and dinners</li></ul><p className="small">Availability and menu options are confirmed directly with our team.</p></div></section><section className="rich-split"><div className="rich-split__image" data-parallax="0.035"><Image src="/images/interior.jpeg" alt="An upstairs Monahan and Fitzgerald event space" fill sizes="(max-width: 760px) 100vw, 50vw" /></div><div className="rich-split__copy"><h2>Gather upstairs.</h2><p>Use the room for the people and moments worth bringing together. Call us to talk through availability, timing, and menu options.</p></div></section><section className="contact-strip"><div className="shell contact-strip__inner"><div><p className="eyebrow eyebrow--gold">Start with a conversation</p><h2>Tell us what you are planning.</h2></div><div className="contact-strip__actions"><a className="button" href={site.phoneHref}>Call {site.phone}</a><Link className="text-link text-link--cream" href="/visit">Visit us first <span>↗</span></Link></div></div></section></> }
